### ISSUE TITLE
question

### ISSUE THREAD

**Issue by qifengle1** [ethanwang9/xia_Yue#1]
请问佬有打包好的bp插件吗？

**Comment by ethanwang9** [comment]
你好，本来想做 xia Yue 的修复工作，修复未授权请求头无法去除的问题，但是修改了半天还是没有搞好就放弃了，其实和 xia Yue 作者 1.2 发的包是一样的，我就不重复打包了。

https://github.com/smxiazi/xia_Yue/releases/tag/1.2

**Comment by qifengle1** [comment]
好叭好叭
